Repository htw-pv3/pvlib-python-pv3, pull requests merged in 2020-07, with the labels that each got.

#8 Feature/openfred pvlib
  .gitignore
  README.md
  config.py
  pv3_main.py
  pv3_pvlib_sonnja.py
  pv3_weatherdata.py
  requirements.yml
Labels: good first issue

#10 add diffuse calculation from notebook #6
  config.py
  pv3_main.py
  pv3_weatherdata.py
Labels: enhancement

#14 Feature/export weather pvsol
  config.py
  pv3_main.py
  pv3_weatherdata.py
Labels: enhancement, fun

#15 Feature/export weather polysun
  config.py
  pv3_main.py
  pv3_weatherdata.py
Labels: enhancement, help wanted

#18 Hotfix/tabulator fix pvsol#16
  config.py
  pv3_main.py
Labels: help wanted

#20 Hotfix/optional append mode#19
  config.py
  pv3_main.py
Labels: enhancement

#23 Hotfix/polysun data order#22
  pv3_main.py
  pv3_weatherdata.py
Labels: help wanted, invalid

#24 Feature/convert open fred#13
  pv3_main.py
  pv3_weatherdata.py
Labels: enhancement, help wanted

#12 search function for pvlib databases#4
  pv3_tools.py
Labels: enhancement, fun
