Repository htw-pv3/pvlib-python-pv3, pull requests merged in 2021-07, with the labels that each got.

#74 Add info about the database of pvlib
  README.md
Labels: documentation, enhancement

#83 Edits in the documentation # 65
  README.md
Labels: documentation

#85 Update README #84
  README.md
Labels: documentation, duplicate

#71 HTW weather data for pvlib simulation #64
  pv3_main.py
Labels: enhancement, fun

#95 Add jupy for result visualiation #29
  pv3_sonnja_results.ipynb
Labels: documentation, enhancement, fun, help wanted

#97 pvlib modelchain documentation #96
  README.md
  pv3_main.py
  pv3_weatherdata.py
Labels: documentation, fun

#104 Feature 102 correcting weatherdata
  pv3_sonnja_pvlib.py
  pv3_weatherdata.py
Labels: help wanted

#121 Release v1.0.0
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  component_import.py
  config.py
  pv3_export_polysun.py
  pv3_export_pvsol.py
  pv3_main.py
  pv3_pvlib_sam_data.ipynb
  pv3_pvlib_sonnja.py
  pv3_sonnja_pvlib.py
  pv3_sonnja_results.ipynb
  pv3_tools.py
  pv3_weatherdata.py
  requirements.yml
  settings.py
Labels: help wanted
